Produce detailed messages in disable preview
alexluigit/dirvish pull request #126
Opened 2022-08-17 08:38 UTC by kngwyu

Hi, thank you for this package!

I often create a new file from `find-file`, and I felt `Preview for ... has been disabled` message incorrect for that 😅

2022-08-17 08:49 UTC, alexluigit approved these changes
Thanks for this!

2022-08-17 08:51 UTC, alexluigit commented on dirvish.el
>  (dirvish-define-preview disable (file)
We can take in the `ext` argument here
```emacs-lisp
(dirvish-define-preview disable (file ext)
```

2022-08-17 08:52 UTC, alexluigit commented on dirvish.el
> +   ((member (downcase (or (file-name-extension file) "")) dirvish-preview-disabled-exts)
Then in here we can use use `(member ext dirvish-preview-disabled-exts)` as the predicate.

2022-08-17 08:56 UTC, alexluigit requested changes
I'm happy to merge this after these small changes are made, thanks!

edit: never mind, I'll take care of this.

2022-08-17 10:01 UTC, merged

2022-08-18 02:32 UTC, kngwyu commented
Thank you for such a quick review!